site_name: ''
site_description: A rate limit module for Ellar
site_url: https://github.com/python-ellar/ellar-throttler
repo_name: python-ellar/ellar-throttler
repo_url: https://github.com/python-ellar/ellar-throttler
edit_uri: blob/master/docs
copyright: |
  Copyright &copy; 2024 <a href="https://github.com/eadwinCode"  target="_blank" rel="noopener">Eadwin Ezeudoh</a>

docs_dir: docs
site_dir: site

theme:
  name: material
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.tooltips
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.prune
#    - navigation.tabs
    - navigation.left
    - navigation.tracking
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: pink
      accent: pink
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: pink
      accent: pink
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode
  font:
    text: Source Sans Pro
    code: Fira Code
  language: en
  logo: img/EllarLogoB.png
  favicon: img/Icon.svg
  icon:
    repo: fontawesome/brands/git-alt

plugins:
  - search:
        separator: '[\s\-,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - minify:
        minify_html: true
  - git-revision-date-localized:
      enable_creation_date: false

nav:
  - Index: index.md

markdown_extensions:
  - attr_list
  - toc:
      permalink: true
  - admonition
  - def_list
  - tables
  - abbr
  - footnotes
  - md_in_html
  - codehilite
  - pymdownx.superfences:
      custom_fences:
      - name: mermaid
        class: mermaid
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.saneheaders
  - pymdownx.tilde

extra_css:
  - stylesheets/extra.css
